# Channels are checked in the order they are listed.

name: ssl-embeddings

channels:
  - pytorch
  - conda-forge
  - nvidia

dependencies:
  - cudatoolkit
  - gdown
  - matplotlib
  - numpy
  - pandas
  - pip
  - python=3.10
  - pytorch
  - pytorch-cuda=11.8
  - scikit-learn
  - torchvision